MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MVC/Models/Friend.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace MVC.Models;

public class Friend
{
	[Required(ErrorMessage = "Отсутствует ID")]
	public Guid Id { get; set; }

	[Required(ErrorMessage = "Введите имя: поле не может быть пустым")]
	public string Name { get; set; }

	[StringLength(25, ErrorMessage = "Допустимо не более 25 символов")]
	public string Place { get; set; }


	[SetsRequiredMembers]
	public Friend(string name, string place)
	{
		Id = Guid.NewGuid();
		Name = name;
		Place = place;
	}
	[SetsRequiredMembers]
	public Friend() { }
}

MVC/Models/FriendRepository.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC.Models;

public class FriendRepository
{
	public List<Friend> Friends { get; set; }
	public FriendRepository()
	{
		Friends =
		[
			new Friend("Влад", "Тверь"),
			new Friend("Никита", "Бобруйск"),
			new Friend("Кеша", "Речица"),
			new Friend("Ярослав", "Волгоград"),
			new Friend("Артём", "Гомель"),
			new Friend("Андрэ Давтян", "Bo_Oston"),
		];
	}
	public List<Friend> GetAll()
	{
		return Friends;
	}
    public Friend Get(Guid id)
    {
		var friend = Friends.Find(x => x.Id == id);
		return friend is not null ? friend : throw new NullReferenceException();
    }
    public void Add(Friend friend)
	{
		Friends.Add(friend);
	}

	public void Edit(Friend friend)
	{
		var index = Friends.FindIndex(x => x.Id == friend.Id);
		if (index == -1)
		{
			throw new InvalidOperationException();
		}
		Friends[index] = friend;
	}
	public void Delete(Guid id)
	{		
		Friends.Remove(Get(id));
	}
}

MVC/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using MVC.Services;


namespace MVC.Controllers;

public class FriendController : Controller
{
	public IFriendRepository Repository;
	public FriendController(IFriendRepository repository)
	{
		Repository = repository;
	}
	[HttpGet]
	public IActionResult Index()
	{
		List<Friend> friends = Repository.GetAll();
		return View(model: friends, viewName: "Index");
	}
	[HttpGet]
	public IActionResult Add()
	{
		return View(viewName: "Add");
	}
	[HttpPost]
	public IActionResult Add([Bind(include: ["Id", "Name", "Place"])] Friend friend)
	{
		if (!ModelState.IsValid)
		{
			return View(friend);
		}
		Repository.Add(friend);	
		return RedirectToAction("Index");
	}
	[HttpGet]
	public IActionResult Edit(Guid id)
	{
		var friend = Repository.Get(id);
		return View(friend);
	}
	[HttpPost]
	public IActionResult Edit(Friend friend)
	{
		if (!ModelState.IsValid)
		{
			return View(friend);
		}
		Repository.Edit(friend);
		return RedirectToAction("Index");
	}
	[HttpGet]
	public IActionResult Delete(Guid id)
	{
		var friend = Repository.Get(id);
		return View(friend);
	}
	[HttpPost]
	public IActionResult Delete(Friend friend)
	{
		Repository.Delete(friend.Id);
		return RedirectToAction("");
	}
}

MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using System.Diagnostics;

namespace MVC.Controllers;

public class HomeController : Controller
{
	private readonly ILogger<HomeController> _logger;

	public HomeController(ILogger<HomeController> logger)
	{
		_logger = logger;
	}

	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Privacy()
	{
		return View();
	}

	[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
	public IActionResult Error()
	{
		return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
	}
}

MVC/Views/Friend/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
	ViewBag.Title = "Add Friend";
}
@model MVC.Models.Friend;
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.1.0/uicons-bold-straight/css/uicons-bold-straight.css'>

<div class="friends-container">
	<div class="header-flex-container">		
		<h1 class="header-in-flex">Добавить друга</h1>
		<button title="Cancel add friend" class="in-header-btn" onclick="location.href='@Url.Action("Index", "Friend")'">
			<i class="header-icon fi fi-bs-cross"></i>
		</button>
	</div>
	
	<form method="post" asp-controller="Friend" asp-action="Add" class="friend-div border">
		<div class="flex-container">
			<div class="flex-item fields-to-fill">
				<div>
					<p class="label">Имя</p>

					<p class="textbox"><input type="text" asp-for="Name" class="border input-text" /></p>
					<span class="label" asp-validation-for="Name"></span>
				</div>
				<div>
					<p class="label">Город</p>
					<p class="textbox"><input type="text" asp-for="Place" class="border input-text" /></p>
					<span class="label" asp-validation-for="Place"></span>
				</div>
			</div>
			<div class="flex-item icons"></div>
		</div>

		

		<p style="margin: 15px 0 0 0"><input class="btn border add-friend" type="submit" value="Добавить друга" /></p>
	</form>
</div>

MVC/Views/Friend/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model MVC.Models.Friend;

<div class="friends-container">
	<h1>Удалить друга?</h1>
	<div >
		<div class="border friend-div">
			<p class="friend-name friend-p">@Model.Name</p>
			<p class="friend-place friend-p">@Model.Place</p>
		</div>
		<form style="margin-bottom:10px" method="post" asp-controller="Friend" asp-action="Delete">
			<input hidden type="text" asp-for="Name" />
			<input hidden type="text" asp-for="Place" />
			<input hidden type="text" asp-for="Id" />
			<input class="btn border btn-yes" type="submit" value="Да" />

		</form>
		<a  class="btn border btn-no" asp-controller="Friend" asp-action="Index">Нет</a>
	</div>
</div>

MVC/Views/Friend/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model MVC.Models.Friend;
@{
}
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.1.0/uicons-bold-straight/css/uicons-bold-straight.css'>

<div class="friends-container">
	<div class="header-flex-container">
		<h1 class="header-in-flex">Редактировать</h1>
		<button title="Cancel add friend" class="in-header-btn" onclick="location.href='@Url.Action("Index", "Friend")'">
			<i class="header-icon fi fi-bs-cross"></i>
		</button>
	</div>

	<form method="post" asp-controller="Friend" asp-action="Edit" class="friend-div border" >
		<input type="text" asp-for="Id" readonly hidden />
		<div class="flex-container">
			<div class="flex-item fields-to-fill">
				<div>
					<p class="label">Имя</p>
					
					<p class="textbox"><input type="text" asp-for="Name" class="border input-text" /></p>
					<span class="label" asp-validation-for="Name"></span>
				</div>
				<div>
					<p class="label">Город</p>
					<p class="textbox"><input type="text" asp-for="Place" class="border input-text" /></p>
					<span class="label" asp-validation-for="Place"></span>
				</div>
			</div>
			<div class="flex-item icons"></div>
		</div>



		<p style="margin: 15px 0 0 0"><input class="btn border add-friend" type="submit" value="Изменить информацию о друге" /></p>
	</form>
</div>

MVC/Views/Friend/Index.cshtml
@model List<MVC.Models.Friend>;

@{
}
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.1.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
<link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.1.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
<div class="friends-container">
	<h1>Мои друзья</h1>
	<div class="flex-row-container">
	@foreach (var friend in Model)
	{
		<div  class="border friend-div flex-container flex-row-item">
			<div>

				<p class="friend-name friend-p">@friend.Name</p>
				<p class="friend-place friend-p">@friend.Place</p>
			</div>
			<div class="icons">
				<div>
					<a class="friend-icon-btn" asp-controller="Friend" asp-action="Edit" asp-route-id="@friend.Id">
						<i class="fi fi-rr-pencil"></i>
					</a>
				</div>
				<div>
					<a class="friend-icon-btn" asp-controller="Friend" asp-action="Delete" asp-route-id="@friend.Id">
						<i class="fi fi-rr-trash"></i>
					</a>
				</div>
			</div>
		</div>
	}
		<input style="align-self: flex-start" class="btn border add-friend flex-row-item" type="button" value="Добавить друга" onclick="location.href='@Url.Action("Add", "Friend")'" />
	</div>
</div>

MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-b navbar-brand " asp-area="" asp-controller="Friend" asp-action="Index">FriendsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Список друзей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Add">Добавить друга</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - FriendsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>